minimumReleaseAgeExclude:
  - '@esportsplus/queue@0.4.6'
  - '@esportsplus/typescript@0.34.4'
  - '@esportsplus/queue@0.4.3 || 0.4.5'
  - '@esportsplus/typescript@0.29.5 || 0.33.4 || 0.34.1'
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
  - '@esportsplus/cli-passthrough@0.0.18'
  - '@esportsplus/utilities@0.28.3'
